language: ruby
dist: trusty
sudo: required
cache: bundler
bundler_args: --without yard guard benchmarks tools
before_script:
  - psql -c 'create database rom_repository' -U postgres
  - rvm get master
script: "bundle exec rake ci"
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-9.1.8.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
    - COVERAGE='true'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
